### ISSUE TITLE
Is there a logging feature?

### ISSUE THREAD

**Issue by bangbaew** [OutThereLabs/actix-web-opentelemetry#121]
![image](https://user-images.githubusercontent.com/29559559/224882467-a2143fba-cc45-4066-b1a2-de4ddacea8fd.png)

I wanna capture these kinds of log (ERROR, INFO, WARN) from the running console, and export them to something like Logstash, but I only find Metrics and Tracing features in the docs.

**Comment by jtescher** [comment]
Logging is not yet supported in the current sdk release, but you can use https://docs.rs/tracing-opentelemetry or other similar crates.

**Comment by jtescher** [comment]
you can now use https://crates.io/crates/opentelemetry-appender-tracing or https://crates.io/crates/opentelemetry-appender-log to send your logs via otel
