### ISSUE TITLE
Get duplicates http_server_active_requests metric after trying to refresh the same path again and again.

### ISSUE THREAD

**Issue by vorrarit** [OutThereLabs/actix-web-opentelemetry#134]
I've tested by using the example provided from the main branch.  I was trying to refresh the same page (e.g. /metrics) again and again, then I found that, after some period of time, http_server_active_requests got duplicated.  I'm not sure whether this is intended behavior or not, but it looks strange for me.

![Screenshot 2566-10-29 at 23 17 59](https://github.com/OutThereLabs/actix-web-opentelemetry/assets/10580902/724bcdb7-7b38-4222-a65b-8630934ebbdc)

**Comment by bangbaew** [comment]
Happens to me as well, I wanna count `http_requests_total` but there's no such metrics that collect requests count for each route, only `http_server_active_requests` which doesn't seem to be useful
![image](https://github.com/OutThereLabs/actix-web-opentelemetry/assets/29559559/f07863b4-1fee-4945-8140-c10f77af4a73)

**Comment by jtescher** [comment]
Think this is related to https://github.com/open-telemetry/opentelemetry-rust/pull/1351

**Comment by jtescher** [comment]
Temporary workaround would be to set workers to 1 as it's creating an instrument per worker currently.

**Comment by jtescher** [comment]
Fixed in latest release https://github.com/open-telemetry/opentelemetry-rust/releases/tag/v0.21.1
