### ISSUE TITLE
Using RequestTracingMiddleware with a TraceContextPropagator.

### ISSUE THREAD

**Issue by allonhadaya** [OutThereLabs/actix-web-opentelemetry#16]
hey :wave: thanks for putting together this crate!

I see you've defined the type `RequestTracingMiddleware` to be generic in terms of an `HttpTextFormat`, and was hoping to use this type like `RequestTracing` does, but with [`TraceContextPropagator`](https://docs.rs/opentelemetry/0.5.0/opentelemetry/api/trace/trace_context_propagator/struct.TraceContextPropagator.html) instead of `B3Propagator`.

In trying to do the above myself, I found that `RequestTracingMiddleware` is public but not exposed in `lib.rs`.

https://github.com/OutThereLabs/actix-web-opentelemetry/blob/5a58b827c1dea03e17b6c18ebc631bb16f367ea8/src/middleware/trace.rs#L130-L135

https://github.com/OutThereLabs/actix-web-opentelemetry/blob/5a58b827c1dea03e17b6c18ebc631bb16f367ea8/src/lib.rs#L68-L73

Have you given thought to how library users can do this, and what the desired api would be? Ideally I could write something as simple as:

```rust
use actix_web_opentelemetry::RequestTracing
...
App::new().wrap(RequestTracing::new(TextContextPropagator::new()))
```

thanks for everything :pray:

**Comment by jtescher** [comment]
@allonhadaya what do you think about https://github.com/OutThereLabs/actix-web-opentelemetry/pull/17, should be best of both worlds, you can use whichever propagator you want and you don't need to specify it here anymore.

**Comment by jtescher** [comment]
Closing this as #17 should fix your issue, feel free to re-open if you have more thoughts.

**Comment by allonhadaya** [comment]
@jtescher I did finally get a chance to try the new code and got everything working through the global propagator api. Thank you so much for your quick reply and code change. The new interface is nice!
