### ISSUE TITLE
Please help with the example

### ISSUE THREAD

**Issue by e-oz** [OutThereLabs/actix-web-opentelemetry#47]
This code (from your example, with 1 small change)
```rust
let (_tracer, _uninstall) = opentelemetry_jaeger::new_pipeline()
      .with_agent_endpoint("localhost:6831")
      .install()
      .expect("pipeline install error");
```
produces this error:
```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
```
In your example, there is no special Tokio runtime created to run this code, and I'd like to avoid it too :)
Could you please give me a hint on how to make it work?

**Comment by jtescher** [comment]
This project is not yet compatible with opentelemetry `v0.12.x`, you can use `v0.11.x` for now and it will work as expected.

**Comment by e-oz** [comment]
Got it, thanks.

**Comment by jtescher** [comment]
@e-oz you should now be able to use v0.10.0 with latest otel 👍, be sure to look at the updated examples to see how to use latest otel with current actix-web
