### ISSUE TITLE
Guidance: Accessing the current span from another middleware

### ISSUE THREAD

**Issue by glademiller** [OutThereLabs/actix-web-opentelemetry#71]
This may not be possible but as of today I haven't found a way to access the context created by this middleware in my own middleware. Is this possible or am I missing something. I have tried ordering my middleware registration in all the combinations I could think of.

I would love some guidance on what might be possible today.

Thank you.

**Comment by jtescher** [comment]
Does adding the `sync-middleware` feature help your case? If not do you have an example of what you are trying to achieve?

**Comment by glademiller** [comment]
Where would I find documentation on the sync-middleware feature?

Ultimately what I am trying to achieve is what this Go middleware is doing:
https://github.com/signalfx/splunk-otel-go/blob/main/instrumentation/net/http/splunkhttp/trace_response_header.go

In order to make that happen I need my middleware to be in the context of the span created by the actix-web-otel middleware or at least have a way to get the trace id and span id for that span.

**Comment by jtescher** [comment]
You can see the addition and minimal docs in https://github.com/OutThereLabs/actix-web-opentelemetry/pull/60. The issue is actix middleware can have logic before returning a future as they are not async functions themselves. If you need to get access to the current otel context outside the future you are returning, you can use this crate's `sync-middleware` flag which sounds like it may help in this case.

**Comment by glademiller** [comment]
It sounds like sync-middleware is exactly what I need. Unfortunately for my purposes right now I'm not going to be able to put the beta version into production to test this out. For now I'll just put my logic into the handler. Thank you for your help.

**Comment by MathieuNls** [comment]
Hello ! Thanks for the response @jtescher.

@glademiller, I am new to everything (rust, actix-web, and open-telemetry overall) and I am wondering if you could share how you managed to get the context in the handler?

Thanks !
