### ISSUE TITLE
Server middleware on the doc doesn't work

### ISSUE THREAD

**Issue by Farkal** [OutThereLabs/actix-web-opentelemetry#8]
I just tried the server middleware example in from the doc and jaeger doesn't find the service and requests.

The client example on this repo work :)

**Comment by jtescher** [comment]
Do you have an example of what is not working? Hard to debug without a few more details

**Comment by Farkal** [comment]
Yes i just use this code (it's the server example on the doc):
```
use actix_web::{web, App, HttpServer};
use actix_web_opentelemetry::RequestTracing;
use opentelemetry::api;

fn init_tracer() {
    opentelemetry::global::set_provider(api::NoopProvider {});
}

async fn index() -> &'static str {
    "Hello world!"
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    init_tracer();
    HttpServer::new(|| {
        App::new()
            .wrap(RequestTracing::default())
            .service(web::resource("/").to(index))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
````
I think it's because there is no provider but it's supposed to try to use the agent on `localhost:6831` no ?

**Comment by jtescher** [comment]
the no op provider is meant to do nothing, it is for testing purposes where you do not want spans created. You have to initialize the provider you want to use in your code (the server example shows a working provider).

**Comment by Farkal** [comment]
Ha ok ! Perhaps add a comment to tell the user that he will see nothing in jaeger if he doesn't set an agent or collector no ?
