### ISSUE TITLE
status code handling for awc client

### ISSUE THREAD

**Issue by Frefreak** [OutThereLabs/actix-web-opentelemetry#87]
It seems currently the client span won't set span status to error when the http request fails in some ways (5xx, 4xx, etc), so the resulting spans' status are always UNSET.  Do you think its reasonable to automatically set the span status according to the http status similar to what golang's contrib `net/http` do? (https://github.com/open-telemetry/opentelemetry-go-contrib/blob/6c86403/instrumentation/net/http/otelhttp/handler.go#L219)

The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status) have this included so at least we have a standard to follow.

**Comment by jtescher** [comment]
@Frefreak yeah that seems like a good idea. Want to take a pass at it?

**Comment by Frefreak** [comment]
Ok. I think I need to first add an http status to span status converting function to the opentelemetry-rust repo if there isn't one already, then apply it here would be trivial.

**Comment by Frefreak** [comment]
PR opened. On a second thought I feels like this doesn't really fit into the opentelemetry-rust repo. For one reason 4xx is different for client and server so it would also needs to take another argument to determine the span kind. Also the basic logic is simple so it feels ok to just included it here for now.
